apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-svc
  name: mysql-svc
spec:
  ports:
  - name: mysql-svc 
    port: 3306
    protocol: TCP
    targetPort: 3306      
  clusterIP: None
  selector:
    app: mysql-sts      
